### ISSUE TITLE
Chat Scrolls when w is pressed

### ISSUE THREAD

**Issue by thecakebandito** [Gabe-Biele/Project-Circleage#14]
1) Press Enter
2) Type message and send
3) Move

--Chat scrolls up?????

**Comment by mccoyrjm** [comment]
In the 'GameWorld' scene, the UICanvas => ChatBoxSV => Scrollbar Vertical object has a component called "Scrollbar (Script)".  That script has a property called 'Navigation' which defines what controls the scrollbar.  By setting this to 'None', the scrollbar only accepts Mouse Click'n'Drag input.

**Comment by mccoyrjm** [comment]
Fixed in commit:

https://github.com/Gabe-Biele/Project-Circleage/commit/52eb7e13aa47e508b995550b1e299fc483238f44
